# config.yaml

# Model and Data Paths (relative paths within the repository)
src_model_path: 'src/models'
data:
  raw:
    training: 'data/raw/training_data.csv'
    test: 'data/raw/test_data.csv'
    outlet_info_path: 'data/raw/outlet_info.csv'
  processed:
    processed_train_data_path: 'data/processed/train.csv'
    processed_test_data_path: 'data/processed/test.csv'
    featured_train_data_output_path: 'data/featured_output/train.csv'
    featured_test_data_output_path: 'data/featured_output/test.csv'
  output:
    output_data: 'data/predicted_output/predicted.csv'
    output_columns: ['date_id', 'store', 'item_dept', 'daily_sales_qty']

data_cleaning:
  max_net_sales: 300000
  max_item_qty: 800
  train_date_id: '2022-02-01'

target_column: 'daily_sales_qty'

feature_engineering:
  rolling_window_sizes: [7, 14]
  lag_days: [1, 2, 3]

model_paths:
  xgboost: 'models/xgboost_model.pkl'
  xgboost_encoders: 'models/xgboost_encoders.pkl'
  arima: 'models/arima_models.pkl'
  lstm: 'models/lstm_model.pkl'

models:
  xgboost:
    n_estimators: 162
    max_depth: 9
    learning_rate: 0.02318117860868824
    colsample_bytree: 0.6
    gamma: 5.0
    min_child_weight: 9
    subsample: 0.6569299424463001
    enable_categorical: True
  arima:
    order: [5, 1, 0]
  lstm:
    units: 50
    epochs: 10

feature_engineering:
  rolling_window_sizes: [7, 14, 30]
  lag_days: [1, 7, 14]

evaluation:
  granularities:
    - 'date_id | store | item_dept'
    - 'date_id | store'

pipeline:
  steps:
    - preprocess
    - build_features
    - train_models
    - evaluate_models

model:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
  lstm:
    units: [64, 32]
    dropout: 0.2
    epochs: 50
    batch_size: 32

features:
  time_features:
    - day_of_week
    - day_of_month
    - month
    - year
    - is_weekend
  lag_features:
    - sales_lag_1
    - sales_lag_7
    - sales_rolling_mean_7
    - sales_rolling_mean_30

target: 'item_qty'

forecast:
  start_date: '2022-02-01'
  end_date: '2022-02-28'
  departments:
    - 'Beverages'
    - 'Grocery'
    - 'Household'
  stores:
    - 'XYZ'
    - 'ABC'

evaluation:
  metric: 'MAPE'
  granularities:
    - ['store', 'department', 'date']
    - ['store', 'date']

train_test_split:
  test_size: 0.2
  random_state: 42

logging:
  level: 'INFO'
  file: 'logs/sales_forecast.log'

model_save_path:
  random_forest: 'models/random_forest_model.pkl'
  lstm: 'models/lstm_model.h5'

app:
  host: '0.0.0.0'
  port: 8501  # Default port for Streamlit
  debug: True
